import asyncio
import sys
from datetime import UTC, datetime

from app.backtester.engine import EventDrivenBacktester
from app.core.database import AsyncSessionLocal, engine
from app.data_sources.postgres_provider import PostgresProvider
from app.indicators.engine import IndicatorEngine


async def execute_asset_backtest(symbol: str) -> None:
    symbol = symbol.upper().strip()
    print(f" Extracting historical tracking segments for Ticker: {symbol}...")

    async with AsyncSessionLocal() as db:
        provider = PostgresProvider(db)

        # 1. Fetch deep historical tracking series from read-only DB layer
        daily_candles = await provider.fetch_historical_candles(
            symbol=symbol,
            timeframe="1D",
            start_ts=datetime(2000, 1, 1, tzinfo=UTC),
            end_ts=datetime(2030, 1, 1, tzinfo=UTC),
        )

        four_hour_candles = await provider.fetch_historical_candles(
            symbol=symbol,
            timeframe="4H",
            start_ts=datetime(2000, 1, 1, tzinfo=UTC),
            end_ts=datetime(2030, 1, 1, tzinfo=UTC),
        )

        if len(daily_candles) < 150:
            print(
                f" Aborting: Found only {len(daily_candles)} daily bars. Minimum lookback pad is 150 rows."
            )
            await engine.dispose()
            return

        print(
            f" -> Retrieved {len(daily_candles)} Daily bars and {len(four_hour_candles)} 4H intervals."
        )

        # 2. Vectorize and calculate indicator metrics over the real historical bars
        print(" Processing indicator arrays via Vector Engine...")
        daily_df = IndicatorEngine.compute_breakout_indicators(daily_candles)
        four_hour_df = IndicatorEngine.compute_breakout_indicators(four_hour_candles)

        # 3. Initialize event simulation model using default friction settings
        print(" Initializing event-driven simulation loop (1% Cash Allocation Risk Rules)...")
        backtester = EventDrivenBacktester(
            initial_balance=100000.0,
            slippage_pct=0.0005,  # 5 bps execution friction markdown
            commission_per_share=0.005,  # Half-penny per share processing cost
        )

        # 4. Process walk-forward historical evaluation
        results = backtester.run_simulation(
            daily_df=daily_df, four_hour_df=four_hour_df, symbol=symbol
        )

        # 5. Output Performance Metrics Summary Report
        print("\n========================================================")
        print(f" BACKTEST PERFORMANCE SUMMARY MATRIX: {symbol}")
        print("========================================================")
        print(f"Initial Starting Capital   : ${results.initial_balance:,.2f}")
        print(f"Final Ending Balance       : ${results.final_balance:,.2f}")
        print(f"Net Growth Return (PnL)    : ${results.total_pnl:,.2f}")
        print(f"Return on Investment (ROI) : {results.return_on_investment:.2f}%")
        print(f"Total Executed Round-Trips : {results.total_trades}")
        print(f"Strategy Win Rate          : {results.win_rate:.2f}%")
        print(f"Maximum Peak Drawdown      : {results.max_drawdown_pct:.2f}%")
        print(f"Annualized Sharpe Ratio    : {results.sharpe_ratio:.2f}")
        print("========================================================")

        if results.trades:
            print("\n RECENT POSITION LOGS (Last 5 Round-Trips Closeouts):")
            print(
                f"{'Direction':<10} | {'Entry Date':<10} | {'Exit Date':<10} | {'Entry Px':<10} | {'Exit Px':<10} | {'Net Profit':<12} | {'Return':<8} | {'Exit Reason'}"
            )
            print("-" * 100)
            for t in results.trades[-5:]:
                print(
                    f"{t.direction:<10} | {t.entry_time.strftime('%Y-%m-%d'):<10} | {t.exit_time.strftime('%Y-%m-%d'):<10} | ${t.entry_price:<9.2f} | ${t.exit_price:<9.2f} | ${t.pnl:<11.2f} | {t.return_pct:>5.2f}% | {t.exit_reason}"
                )
        else:
            print(
                "\n Strategy Execution Parameters Note: 0 historical entry signals were generated by the rules engine."
            )

    await engine.dispose()


if __name__ == "__main__":
    target_ticker = sys.argv[1] if len(sys.argv) > 1 else "A"
    asyncio.run(execute_asset_backtest(target_ticker))
