"""add_compound_indices_on_candles

Revision ID: 39ef9777b854
Revises: 077e5ebef086
Create Date: 2026-05-17 13:59:08.555452

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39ef9777b854"
down_revision: str | None = "077e5ebef086"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_symbol_tf_ts", "candles", ["symbol", "timeframe", "ts"], unique=False)
    op.create_index(op.f("ix_candles_timeframe"), "candles", ["timeframe"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candles_timeframe"), table_name="candles")
    op.drop_index("idx_symbol_tf_ts", table_name="candles")
    # ### end Alembic commands ###
